---
abstract: 'Deprecated FFTW version 2 bindings for PDL'
author:
  - 'Chris Marshall <chm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  PDL: 2.007
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  PDL: 2.007
dynamic_config: 1
generated_by: 'Chris Marshall, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-FFTW
no_index:
  directory:
    - t
    - inc
provides:
  PDL::FFTW:
    file: fftw.pd
requires:
  PDL: 2.007
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=PDL-FFTW
  homepage: http://pdl.perl.org/
  license: http://cpansearch.perl.org/src/CHM/PDL-2.007/COPYING
  repository: git://git.code.sf.net/p/pdl/pdl-fftw
version: 2.021
