---
abstract: unknown
author:
  - unknown
build_requires:
  PDL: 2.004
configure_requires:
  PDL: 2.004
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-FFTW
no_index:
  directory:
    - t
    - inc
requires:
  PDL: 2.004
resources:
  bugtracker: http://sourceforge.net/p/pdl/bugs/
  homepage: http://pdl.perl.org/
version: 2.016_02
